### ISSUE TITLE
Possibility to rename `n` to `node2`

### ISSUE THREAD

**Issue by giltayar** [weiran-zsd/eslint-plugin-node#5]
Sorry for the bikeshedding, but "`n`" sounds a bit minimal. Especially in the ESlint configuration rules.

I believe any name would be suboptimal, but having the weird `node` in the name would, I believe be beneficial.

Something like `node2` or `node-new`?

**Comment by voxpelli** [comment]
I would prefer sticking to the current name rather than causing more fragmentation.

Changing names of a module is hard to do without breaking all of the update flows of dependent projects.

**Comment by aladdin-add** [comment]
I agreed the current name is not ideal(I tried `eslint-plugin-nd` while it has been taken ＞︿＜). As of now, I'm standing with @voxpelli - It's not always an easy thing to renaming a package, for users and maintainers.

**Comment by giltayar** [comment]
Good to hear that people are already using this package! Once I get the esm resolution in, I'll probably also migrate our company to use this fork.

Thanks for the hard work, and closing for lack of public interest. ☺️

**Comment by gpoole** [comment]
Just to throw in my 2c as a random user: I was about to open a PR on the eslint-config-standard readme because I thought the sample command to install peer dependencies had a typo in it. The name looking like a truncated version of an existing well-known package name is bound to be confusing people.

While it is a pain to rename it's only going to get harder as time goes on. Leaving the old package name published with a deprecation notice and publishing under a new name shouldn't be too bad should it? No different to publishing a major release in terms of work needed by people downstream?

**Comment by aladdin-add** [comment]
but we (other contributors) don't have the access to publish - if we do, I'd prefer taking over, instead of forking. 😂

**Comment by aladdin-add** [comment]
eslint-plugin-node.

**Comment by gpoole** [comment]
I meant that the discussion here seemed to be saying that you can't rename this module from `eslint-plugin-n` because it will break things? I was asking is publishing a deprecation notice under `eslint-plugin-n` and publishing this under something less ambiguous like `eslint-plugin-node2` so bad? Better yet what about a scoped name like `@eslint-community/eslint-plugin-node` as per https://github.com/weiran-zsd/eslint-plugin-node/issues/8? I think it would help a lot with comprehension over the current name.

Again I came here specifically for the same reason as @giltayar mentioned in the original issue: I was confused by the name because it looked like a mistake to me and wanted to suggest changing it to avoid confusion.

**Comment by aladdin-add** [comment]
I'm 👍 to `@eslint-community/eslint-plugin-node`. just waiting for the `@eslint-community` get ready.

**Comment by giltayar** [comment]
+1 for anything _but_ `eslint-plugin-n`. 😃

**Comment by voxpelli** [comment]
The current name works until `@eslint-community/eslint-plugin-node` or merging into upstream becomes a possibility.

**Comment by voxpelli** [comment]
As I commented in #8, there is now an ESLint RFC up regarding creating the `@eslint-community`: https://github.com/eslint/rfcs/pull/91
